name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag epenguincom/nitter:$(date +%Y%m%d) --tag epenguincom/nitter:latest

    - name: Push the Docker image (latest)
      run: docker push epenguincom/nitter:latest

    - name: Push the Docker image (timestamped)
      run: docker push epenguincom/nitter:$(date +%Y%m%d)
